import '@/assets/css/globals.css';
import { getDictionary } from '@/dictionaries/dictionaries';
import StoreProvider from '@/store/StoreProvider';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import React from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});
export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'vi' }];
}
export const metadata: Metadata = {
  title: 'Hai Trieu Portfolio',
  description: 'Generated by create Hai Trieu',
};

export default async function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  const dict = await getDictionary(lang);
  return (
    <html lang={lang}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider lang={lang} dict={dict}>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
